#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const { resolveScriptPath } = require('./runtime/script-resolver');
const { runTurns } = require('./runtime/ai-dungeon-mimic');
function parseArgs(argv) { const args = { script: '', input: '', output: '', caseFile: '', out: '', hookTimeoutMs: 1800, scriptTimeoutMs: 2200, noContext: false, includeState: false, includeStoryCards: false, pretty: true }; for (let i=2;i<argv.length;i+=1) { const a=argv[i]; if (a==='--script') args.script=argv[++i]||''; else if (a==='--input'||a==='--player') args.input=argv[++i]||''; else if (a==='--output'||a==='--story') args.output=argv[++i]||''; else if (a==='--case') args.caseFile=argv[++i]||''; else if (a==='--out') args.out=argv[++i]||''; else if (a==='--hook-timeout-ms') args.hookTimeoutMs=Number(argv[++i]||args.hookTimeoutMs)||args.hookTimeoutMs; else if (a==='--script-timeout-ms') args.scriptTimeoutMs=Number(argv[++i]||args.scriptTimeoutMs)||args.scriptTimeoutMs; else if (a==='--no-context') args.noContext=true; else if (a==='--include-state') args.includeState=true; else if (a==='--include-storycards') args.includeStoryCards=true; else if (a==='--compact') args.pretty=false; else if (a==='--help'||a==='-h') args.help=true; } return args; }
function help() { console.log(`AIDRPG AI Dungeon mimic quick runner\n\nUsage:\n  node aid-mimic.js --script ./aidrpg-script.js --input "I pick up the key" --output "You pick up the key."\n  node aid-mimic.js --case ./examples/mimic-case.json\n\nCase file format:\n  { "turns": [{ "input": "I take the key.", "output": "You take the key." }] }\n\nThis is intentionally small and ChatGPT-safe: one process, bounded hook timeouts, compact JSON output.`); }
function loadTurns(args) { if (args.caseFile) { const parsed=JSON.parse(fs.readFileSync(path.resolve(args.caseFile),'utf8')); if (Array.isArray(parsed)) return parsed; if (parsed && Array.isArray(parsed.turns)) return parsed.turns; throw new Error('Case file must be an array or an object with a turns array.'); } return [{ input: args.input, output: args.output, runContext: !args.noContext }]; }
function main() { const args=parseArgs(process.argv); if (args.help) return help(); const resolved=resolveScriptPath(args.script); if (!resolved.scriptPath) { console.error('Could not find an AIDRPG script. Pass --script /path/to/script.txt or set AIDRPG_SCRIPT.'); process.exit(2); } const result=runTurns(resolved.scriptPath, loadTurns(args), { hookTimeoutMs: args.hookTimeoutMs, scriptTimeoutMs: args.scriptTimeoutMs, runContext: !args.noContext, includeState: args.includeState, includeStoryCards: args.includeStoryCards, stopOnError: false }); result.scriptPath=resolved.scriptPath; result.scriptSource=resolved.source; const json=JSON.stringify(result,null,args.pretty?2:0); if (args.out) fs.writeFileSync(path.resolve(args.out), json+'\n'); console.log(json); process.exit(result.results.some(r=>!r.ok)?1:0); }
main();
